# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: a5a810c4db6d7d636b4a94c1bf94f667
  secret_key: b6bdff8e6c705e6ce2bab5fdfebd0cf4
  canvas_page_name:
  callback_url: http://tonyzito.homeip.net/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3001
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
    api_key: a5a810c4db6d7d636b4a94c1bf94f667
    secret_key: b6bdff8e6c705e6ce2bab5fdfebd0cf4
    canvas_page_name:
    callback_url: http://204.232.206.167/
    pretty_errors: true
    set_asset_host_to_callback_url: false
    tunnel:
      public_host_username: 
      public_host: 
      public_port: 4007
      local_port: 3000
      server_alive_interval: 0
